# Generated by Django 3.2.6 on 2021-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('uname', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
