# Generated by Django 3.2.6 on 2021-08-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
    ]
