# Generated by Django 3.2.6 on 2021-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_remove_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.CharField(max_length=70),
        ),
    ]
