# Generated by Django 3.2.5 on 2021-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_auto_20210820_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='uname',
            new_name='username',
        ),
    ]
