# Generated by Django 3.2.5 on 2021-08-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_rename_uname_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pincode',
        ),
    ]
