# Generated by Django 3.2.5 on 2021-08-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_auto_20210826_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uname',
        ),
    ]
