# Generated by Django 3.2.5 on 2021-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_remove_order_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sequence_id',
            field=models.IntegerField(default=0),
        ),
    ]
