# Generated by Django 3.0.6 on 2021-08-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_auto_20210826_1626'),
        ('myproject', '0013_product_sequence_id'),
    ]

    operations = [
    ]
