# Generated by Django 3.2.6 on 2021-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_merge_20210828_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
